package app.filterpod

/**
 * Span and coverage math for the native filter engine.
 *
 * A line-for-line port of src/core/filterMath.ts and the span helpers in
 * buildFilterMap.ts, in the seconds domain the TS code uses — conversion to the
 * millisecond domain the player runs on happens only at the service boundary. The two
 * implementations are held identical by golden-fixture tests (SpanMathParityTest):
 * vectors generated by the TS code must reproduce byte-identically here. Change either
 * side only together.
 */

data class Range(val startSec: Double, val endSec: Double)

data class EngineSpan(
    val startSec: Double,
    val endSec: Double,
    val severity: String,
    val category: String,
    val terms: List<String>,
)

data class TimedWord(val word: String, val startSec: Double, val endSec: Double)

object SpanMath {

    /** Sorts and merges analyzed ranges, joining ones that touch. */
    fun mergeRanges(ranges: List<Range>): List<Range> {
        if (ranges.isEmpty()) return emptyList()
        val sorted = ranges.sortedBy { it.startSec }
        val out = ArrayList<Range>(sorted.size)
        out.add(sorted[0])
        for (i in 1 until sorted.size) {
            val range = sorted[i]
            val last = out.last()
            // Touching counts as contiguous: chunk N ends exactly where chunk N+1 begins.
            if (range.startSec <= last.endSec) {
                if (range.endSec > last.endSec) {
                    out[out.size - 1] = last.copy(endSec = range.endSec)
                }
            } else {
                out.add(range)
            }
        }
        return out
    }

    /** Removes [holes] from [ranges]. */
    fun subtractRanges(ranges: List<Range>, holes: List<Range>): List<Range> {
        if (holes.isEmpty()) return mergeRanges(ranges)
        val cuts = mergeRanges(holes)
        var out = mergeRanges(ranges)

        for (hole in cuts) {
            val next = ArrayList<Range>(out.size + 1)
            for (range in out) {
                if (hole.endSec <= range.startSec || hole.startSec >= range.endSec) {
                    next.add(range)
                    continue
                }
                if (hole.startSec > range.startSec) {
                    next.add(Range(range.startSec, hole.startSec))
                }
                if (hole.endSec < range.endSec) {
                    next.add(Range(hole.endSec, range.endSec))
                }
            }
            out = next
        }
        return out.filter { it.endSec > it.startSec }
    }

    /** Whether a moment has been analyzed, and is therefore safe to play. */
    fun isAnalyzed(ranges: List<Range>, positionSec: Double): Boolean =
        ranges.any { positionSec >= it.startSec && positionSec < it.endSec }

    /**
     * How far playback can safely run from [positionSec] — the end of the contiguous
     * coverage containing it, or [positionSec] itself when not analyzed at all.
     */
    fun analyzedUntil(ranges: List<Range>, positionSec: Double): Double {
        for (range in ranges) {
            if (positionSec >= range.startSec && positionSec < range.endSec) return range.endSec
        }
        return positionSec
    }

    /** Total analyzed audio. */
    fun analyzedSec(ranges: List<Range>): Double =
        ranges.sumOf { maxOf(0.0, it.endSec - it.startSec) }

    fun severityRank(severity: String): Int = when (severity) {
        "strong" -> 3
        "moderate" -> 2
        else -> 1
    }

    /** Sorts by start and merges overlapping or near-adjacent spans into single skips. */
    fun normalizeSpans(spans: List<EngineSpan>, mergeGapSec: Double = 0.35): List<EngineSpan> {
        if (spans.isEmpty()) return emptyList()
        val sorted = spans.sortedBy { it.startSec }
        val out = ArrayList<MutableSpan>(sorted.size)
        out.add(MutableSpan(sorted[0]))

        for (i in 1 until sorted.size) {
            val span = sorted[i]
            val last = out.last()
            if (span.startSec - last.endSec <= mergeGapSec) {
                last.endSec = maxOf(last.endSec, span.endSec)
                // A merged span carries the strongest severity of its parts.
                if (severityRank(span.severity) > severityRank(last.severity)) {
                    last.severity = span.severity
                    last.category = span.category
                }
                for (term in span.terms) {
                    if (term !in last.terms) last.terms.add(term)
                }
            } else {
                out.add(MutableSpan(span))
            }
        }
        return out.map { it.toSpan() }
    }

    /** Total audio removed by a set of spans. */
    fun totalSkippedSec(spans: List<EngineSpan>): Double =
        spans.sumOf { maxOf(0.0, it.endSec - it.startSec) }

    /** Applies padding to a raw word timing; see filterMath.ts padSpan for the why. */
    fun padSpan(
        startSec: Double,
        endSec: Double,
        padBeforeSec: Double,
        padAfterSec: Double,
        durationSec: Double?,
    ): Range {
        val start = maxOf(0.0, startSec - padBeforeSec)
        val end = if (durationSec != null) minOf(durationSec, endSec + padAfterSec) else endSec + padAfterSec
        return Range(start, end)
    }

    /**
     * Ceiling on how much audio a single matched word may remove; mirrors
     * MAX_MATCH_SEC in buildFilterMap.ts — a mistimed whisper token is capped rather
     * than trusted, because silently deleting a stretch of the show is the worst
     * failure this app can have.
     */
    const val MAX_MATCH_SEC = 1.5

    /** Turns matched words into padded, merged skip spans. Port of spansFromMatches. */
    fun spansFromMatches(
        matches: List<WordMatcher.Match>,
        padBeforeSec: Double,
        padAfterSec: Double,
        mergeGapSec: Double,
        durationSec: Double?,
    ): List<EngineSpan> {
        val spans = matches.map { match ->
            val cappedEnd = minOf(match.word.endSec, match.word.startSec + MAX_MATCH_SEC)
            val padded = padSpan(match.word.startSec, cappedEnd, padBeforeSec, padAfterSec, durationSec)
            EngineSpan(
                startSec = padded.startSec,
                endSec = padded.endSec,
                severity = match.severity,
                category = match.category,
                terms = listOf(match.term),
            )
        }
        return normalizeSpans(spans, mergeGapSec)
    }

    /** Two emissions of the same word closer than this are the same utterance. */
    private const val DUPLICATE_WINDOW_SEC = 0.35

    /** Floor for a word whose ASR timings are inverted or zero-width. */
    private const val MIN_WORD_SEC = 0.12

    /**
     * Normalizes raw ASR output into the ordered, deduplicated sequence the matcher
     * assumes. Port of sortAndDedupe in buildFilterMap.ts; see that comment for the
     * two whisper defects (chunk-overlap re-emission, inverted DTW timings) it fixes.
     */
    fun sortAndDedupe(words: List<TimedWord>): List<TimedWord> {
        val sorted = words
            .map { word ->
                if (word.endSec > word.startSec) word
                else word.copy(endSec = word.startSec + MIN_WORD_SEC)
            }
            .sortedBy { it.startSec }

        val out = ArrayList<TimedWord>(sorted.size)
        for (word in sorted) {
            val previous = out.lastOrNull()
            if (
                previous != null &&
                previous.word == word.word &&
                kotlin.math.abs(previous.startSec - word.startSec) < DUPLICATE_WINDOW_SEC
            ) {
                // Keep the wider of the two, so padding is never based on a clipped copy.
                if (word.endSec > previous.endSec) {
                    out[out.size - 1] = previous.copy(endSec = word.endSec)
                }
                continue
            }
            out.add(word)
        }
        return out
    }

    private class MutableSpan(span: EngineSpan) {
        val startSec = span.startSec
        var endSec = span.endSec
        var severity = span.severity
        var category = span.category
        val terms = span.terms.toMutableList()
        fun toSpan() = EngineSpan(startSec, endSec, severity, category, terms.toList())
    }
}
