package app.filterpod.shared.filter

import app.filterpod.shared.data.DEFAULT_PROFILES
import app.filterpod.shared.model.Category
import app.filterpod.shared.model.Severity
import app.filterpod.shared.model.WordOverride
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * The compiler must produce the exact wordlist the TypeScript compiler produced —
 * the fixture is generated by exportParityFixtures.test.ts from the real
 * implementation, overrides and all. A drift here means the two apps filter the
 * same audio differently.
 */
class WordlistCompilerParityTest {

    private val fixtures: JsonObject by lazy {
        val stream = checkNotNull(javaClass.classLoader.getResourceAsStream("filter-fixtures.json")) {
            "filter-fixtures.json missing — regenerate with FILTER_FIXTURES=1 npx vitest run exportParityFixtures"
        }
        Json.parseToJsonElement(stream.readBytes().decodeToString()).jsonObject
    }

    private val standardOverrides = listOf(
        WordOverride("holy guacamole", WordOverride.ACTION_BLOCK, Severity.MODERATE, Category.CUSTOM),
        WordOverride("frak", WordOverride.ACTION_BLOCK, Severity.MODERATE, Category.CUSTOM),
        WordOverride("uryy", WordOverride.ACTION_ALLOW, Severity.MILD, Category.BLASPHEMY),
    )

    private fun assertCompiledMatchesFixture(fixtureName: String, compiled: CompiledWordlist) {
        val expected = fixtures["wordlists"]!!.jsonObject[fixtureName]!!.jsonObject
        val actual = compiled.toEngineJson()

        // exact: same normalized->(term,severity,category) mapping, order-insensitive.
        fun exactMap(o: JsonObject) = o["exact"]!!.jsonArray.associate { row ->
            row.jsonObject["normalized"]!!.jsonPrimitive.content to Triple(
                row.jsonObject["term"]!!.jsonPrimitive.content,
                row.jsonObject["severity"]!!.jsonPrimitive.content,
                row.jsonObject["category"]!!.jsonPrimitive.content,
            )
        }
        assertEquals(exactMap(expected), exactMap(actual), "exact map diverged for $fixtureName")

        // phrases: order matters to the matcher only by length; compare as sets of rows.
        fun phraseSet(o: JsonObject) = o["phrases"]!!.jsonArray.map { row ->
            row.jsonObject["words"]!!.jsonArray.joinToString(" ") { it.jsonPrimitive.content } +
                "|" + row.jsonObject["term"]!!.jsonPrimitive.content +
                "|" + row.jsonObject["severity"]!!.jsonPrimitive.content
        }.toSet()
        assertEquals(phraseSet(expected), phraseSet(actual), "phrases diverged for $fixtureName")

        fun stringSet(o: JsonObject, key: String) =
            o[key]!!.jsonArray.map { it.jsonPrimitive.content }.toSet()
        assertEquals(stringSet(expected, "allowed"), stringSet(actual, "allowed"))
        assertEquals(stringSet(expected, "neverFlag"), stringSet(actual, "neverFlag"))
    }

    @Test
    fun standardProfileWithOverridesMatchesTypeScript() {
        val standard = DEFAULT_PROFILES.first { it.id == "standard" }
        assertCompiledMatchesFixture("standard", compileWordlist(standard, standardOverrides))
    }

    @Test
    fun familyProfileMatchesTypeScript() {
        val family = DEFAULT_PROFILES.first { it.id == "family" }
        assertCompiledMatchesFixture("family", compileWordlist(family))
    }

    @Test
    fun normalizeMatchesTypeScript() {
        for (case in fixtures["normalizeCases"]!!.jsonArray) {
            val raw = case.jsonObject["raw"]!!.jsonPrimitive.content
            val expected = case.jsonObject["normalized"]!!.jsonPrimitive.content
            assertEquals(expected, normalizeWord(raw), "normalizeWord('$raw')")
        }
    }

    @Test
    fun offProfileCompilesEmpty() {
        val off = DEFAULT_PROFILES.first { it.id == "off" }
        val compiled = compileWordlist(off)
        assertTrue(compiled.exact.isEmpty())
        assertTrue(compiled.phrases.isEmpty())
    }
}
